### ISSUE TITLE
jsonave("$") not passing root object for jsonave 3.0 using but works only with jsonave 2.0

### ISSUE THREAD

**Issue by SameerSiddiqui** [amida-tech/jsonave#4]
Hello- I have been using jsonave with another project called jsonapter- jsonapter uses jsonave 2.0

I recently updated to jsonave 3.0- After updating i am facing an issue-

We use to write jsonave("$") to access the root object.

It was working fine with jsonave 2.0- but after the update to 3.0 jsonave("$") is not giving me root object  instead i get null value and because of that my properties don't get mapped. if i completely remove jsonave("$") then i get the root object- 

it's not a show stopper but i have to go back to every mapping and update the templates and remove jsonave("$") to pass in the entire object.

As of now jsonapter uses jsonave 2.0 - I started facing this issue when i switched to jsonave 3.0.  By they way it works fine with jsonave 2.0

sample code: jsonave 2.0  ( works fine but breaks with jsonave 3.0)

contactRules:{
                            content:{
                                contactRule: {
                                    dataKey: jsonave("$"), value: _setPlatformContactRules
                                }
                            }
                        }

with jsonave 3.0 contactRules will not get mapped because the function _setPlatformContactRules will receive null-

with jsonave 3.0  (works fine)

contactRules:{
                            content:{
                                contactRule: {
                                    value: _setPlatformContactRules
                                }
                            }
                        }

Can you please update jsonapter with jsonave 3.0 and run the test cases with jsonave("$") and check if they pass- 

Thanks,
Sameer

**Comment by SameerSiddiqui** [comment]
Just a quick update- it will work if we wrap it inside object like this jsonave({path:"$"}) this works and this jsonave("$") doesn't-

**Comment by au2** [comment]
I think I changed "$" behaviour to be compatible with the other JSONPath package.  Can you just do a global replace in your templates? jsonave("$") -> null should work if removing all dataKey: jsonave("$") is too much work.

**Comment by SameerSiddiqui** [comment]
Alright, Thank-you for the update.
